export const API_BASE = "http://127.0.0.1:8000";

export const api = {
  reloadStatus: jest.fn().mockResolvedValue({
    workspace_slug: "loregarden",
    supported: false,
    ready: false,
    blockers: [],
    active_agent_runs: [],
    active_orchestrations: [],
    running_workflow_tickets: [],
  }),
  reloadServer: jest.fn().mockResolvedValue({ triggered: true, at: "" }),
  health: jest.fn().mockResolvedValue({}),
  workspaces: jest.fn().mockResolvedValue([]),
  ticketTree: jest.fn().mockResolvedValue([]),
  tickets: jest.fn().mockResolvedValue([]),
  ticket: jest.fn(),
  updateTicket: jest.fn(),
  workflowTemplates: jest.fn().mockResolvedValue([]),
  workspaceWorkflow: jest.fn().mockResolvedValue(null),
  approvals: jest.fn().mockResolvedValue([]),
  runs: jest.fn().mockResolvedValue([]),
  runLog: jest.fn(),
  runMessages: jest.fn(),
  ticketLedger: jest.fn(),
  mcpServers: jest.fn(),
  mcpTelemetry: jest.fn(),
  createMcpServer: jest.fn(),
  updateMcpServer: jest.fn(),
  deleteMcpServer: jest.fn(),
  sendRunMessage: jest.fn(),
  triage: jest.fn().mockResolvedValue({
    pending_approvals: [],
    recent_approvals: [],
    messages: [],
    runtime: {
      cli_adapter: "",
      claude_model: "",
      cursor_model: "",
      lmstudio_base_url: "",
      lmstudio_model: "",
    },
  }),
  runtimeOptions: jest.fn().mockResolvedValue([]),
  usage: jest.fn().mockResolvedValue({}),
  memoryConfig: jest.fn().mockResolvedValue({}),
  setMemoryConfig: jest.fn(),
  orchestrate: jest.fn(),
  openPr: jest.fn(),
  startRun: jest.fn(),
  advance: jest.fn(),
  routeWorkflow: jest.fn(),
  resolveApproval: jest.fn(),
  setWorkspaceTemplate: jest.fn(),
  setWorkspaceRuntime: jest.fn(),
  createWorkspace: jest.fn(),
  previewTicketImportPaths: jest.fn(),
  importTickets: jest.fn(),
  createTicket: jest.fn(),
  createTicketStudioSession: jest.fn(),
  browseImportDirectory: jest.fn().mockResolvedValue([]),
};
