#!/usr/bin/env python3
"""Insert or refresh loregarden's managed control-plane section in a workspace AGENTS.md.

The hook installer's sibling. That one teaches a workspace's *commits* about
loregarden's rules; this one teaches its *agents* about loregarden's tools — the
half that was missing. An agent opened in blobert or lore-eden reads that repo's
AGENTS.md and, until this block is there, has no way to learn that the ticket it
was asked about lives in a database it can reach, not a file it can grep for.

The block is delimited by markers and rewritten in place, so re-running is safe
and the workspace's own content is never touched. Paths inside it are absolute
into this checkout, for the same reason the hook block references rather than
copies: a copy in each repo is a copy that drifts.

Stdlib only — this runs against arbitrary workspaces, which may have no venv.
"""

from __future__ import annotations

import argparse
from pathlib import Path

BEGIN_MARKER = "<!-- >>> loregarden control plane (managed) >>> -->"
END_MARKER = "<!-- <<< loregarden control plane (managed) <<< -->"

SLUG_PLACEHOLDER = "<workspace-slug>"

#: The slug is rendered into the CLI examples, so a refresh has to know the one
#: the block was installed with. Nothing else in the workspace records it, and a
#: `--check` that re-derived the placeholder would report a current block as
#: outdated forever. So the block carries it.
SLUG_FIELD = "loregarden-workspace-slug:"

#: Written when the workspace has no AGENTS.md at all. Deliberately thin: this
#: file belongs to the workspace, and inventing content about a repo we know
#: nothing about would be worse than an empty frame.
NEW_FILE_HEADER = [
    "# AGENTS.md",
    "",
    "Operating notes for coding agents in this repository.",
    "",
]


def render_block(loregarden_root: Path, workspace_slug: str) -> list[str]:
    cli = loregarden_root / "scripts" / "loregarden-cli.sh"
    asset = loregarden_root / "agent_context" / "agents" / "common_assets" / "loregarden_mcp_v1.md"
    return [
        BEGIN_MARKER,
        f"<!-- {SLUG_FIELD} {workspace_slug} -->",
        "<!-- Generated by loregarden's scripts/install-workspace-docs.sh — do not edit by",
        "     hand; re-run that script to refresh. The source lives in loregarden. -->",
        "",
        "## Loregarden control plane",
        "",
        "This repository is a **loregarden workspace**. Its tickets, workflow stages,",
        "checkpoints, learnings and artifacts live in loregarden's database — not in files",
        "here. There is no ticket markdown to find: searching the repo for one returns",
        "nothing and means nothing.",
        "",
        "### Reaching it",
        "",
        "Native MCP tools, named `mcp__loregarden__<tool>` in Claude Code, when the",
        "`loregarden` server is attached. When it is not, every tool also runs in-process",
        "against the database, from any directory:",
        "",
        "```bash",
        f"{cli} mcp list                       # every tool + description",
        f"{cli} mcp describe loregarden_get_ticket",
        f"{cli} mcp call loregarden_get_ticket external_id=<slug> workspace_slug={workspace_slug}",
        "```",
        "",
        "Arguments are `key=value`, typed from each tool's own schema; `describe` lists the",
        "accepted names, so guess none. Long values go in a file and are passed as",
        "`content=@path`. Exit codes: `0` ok, `1` the tool failed, `2` you invoked it wrong.",
        "Do not hand-write JSON-RPC against the HTTP endpoint, and do not abandon a",
        "control-plane write because no MCP tool is listed.",
        "",
        "### Never report your work as a markdown file",
        "",
        "Loregarden reads no `*_FINDINGS.md`, `*_COMPLETION.md`, `*_REPORT.md`, summary or",
        "sign-off file. One written here is invisible to the control plane, and gets swept",
        "into an unrelated ticket's commit by the orchestrator.",
        "",
        "| To record… | Use | Not |",
        "|---|---|---|",
        "| Findings, analysis, test output, review report | `loregarden_attach_artifact` | a `*.md` file |",
        "| Stage outcome (pass / reject / blocked) | the `<<<LOREGARDEN_STAGE_REPORT>>>` sentinel, or `loregarden_complete_stage` | a `*_COMPLETION.md` |",
        "| An assumption or ambiguity you resolved alone | `loregarden_append_checkpoint` | a checkpoint file |",
        "| Learnings, anti-patterns | `loregarden_append_learning` | `LEARNINGS.md` |",
        "| Spec, description, acceptance criteria | `loregarden_update_ticket` | a spec `.md` |",
        "| An unrecoverable blocker | `loregarden_block_ticket` | giving up quietly |",
        "",
        "Writing real source and real tests is of course still the job — this is about",
        "*reports about* the work. Short findings belong in your response text.",
        "",
        "### Other tools worth knowing",
        "",
        "| Situation | Tool |",
        "|---|---|",
        "| Find tickets by title/slug, list siblings or children | `loregarden_list_tickets` |",
        "| Human sign-off needed | `loregarden_request_approval` |",
        "| Ask what the organization gates will say, before spending a stage | `loregarden_check_organization` |",
        "| Read framework or library docs (cached; cheaper than WebFetch) | `loregarden_search_reference`, then `loregarden_fetch_reference` |",
        "| Starting containers outside a stage that declared a footprint | `loregarden_reserve_docker_capacity`, then release it |",
        "| Prior art from other tickets, memory | `loregarden_search_prior_work`, `loregarden_search_memory` |",
        "",
        "### Gates",
        "",
        "Loregarden's organization, silent-failure and UX guardrails run against this",
        "repository — as this repo's pre-commit hooks (via",
        "`scripts/install-workspace-hooks.sh`) and again at every orchestration stage",
        "transition. They are diff-scoped, so inherited debt is not your commit's problem.",
        "A gate your change trips is part of your change: fix the cause, never `--no-verify`.",
        "Waive a genuine exception on the line, with a substantive reason —",
        "`# py-silent: allow`, `# py-org: allow-string`, `// ts-org: allow-instanceof`,",
        "`silent-ok:`, `ux-ok:`.",
        "",
        f"Full agent-facing reference: `{asset}`",
        END_MARKER,
    ]


def strip_managed_block(lines: list[str]) -> tuple[list[str], list[str]]:
    """Split out the existing managed block, if any. Returns (rest, block)."""
    out: list[str] = []
    block: list[str] = []
    inside = False
    for line in lines:
        if line.strip() == BEGIN_MARKER:
            inside = True
            block.append(line)
            continue
        if line.strip() == END_MARKER:
            inside = False
            block.append(line)
            continue
        (block if inside else out).append(line)
    return out, block


def slug_in(block: list[str]) -> str | None:
    """The slug an existing block was installed with, if it records one."""
    for line in block:
        stripped = line.strip()
        if stripped.startswith(f"<!-- {SLUG_FIELD}") and stripped.endswith("-->"):
            value = stripped[len(f"<!-- {SLUG_FIELD}") : -len("-->")].strip()
            if value:
                return value
    return None


def compose(rest: list[str], block: list[str]) -> list[str]:
    """Managed block last, separated from the workspace's own content by one blank line."""
    body = list(rest)
    while body and not body[-1].strip():
        body.pop()
    if body:
        body.append("")
    return [*body, *block]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--agents-file", required=True)
    parser.add_argument("--loregarden-root", required=True)
    parser.add_argument(
        "--workspace-slug",
        default=None,
        help=(
            "Slug loregarden knows this workspace by; used in the CLI examples. "
            "Omitted, the slug already recorded in the block is kept."
        ),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    target = Path(args.agents_file)
    existed = target.exists()
    original = target.read_text(encoding="utf-8").splitlines() if existed else list(NEW_FILE_HEADER)
    rest, existing = strip_managed_block(original)

    slug = args.workspace_slug or slug_in(existing) or SLUG_PLACEHOLDER
    block = render_block(Path(args.loregarden_root), slug)
    updated = compose(rest, block)

    if existed and updated == original:
        print(f"ok: {target} already current")
        return 0
    if args.check:
        if not existed:
            state = "missing file"
        elif existing:
            state = "outdated"
        else:
            state = "missing"
        print(f"{state}: {target} managed section")
        return 1

    target.write_text("\n".join(updated) + "\n", encoding="utf-8")
    if not existed:
        print(f"created: {target}")
    else:
        print(f"{'refreshed' if existing else 'installed'}: {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
