#!/usr/bin/env python3
"""Insert or refresh loregarden's managed hook block in a workspace lefthook.yml.

Splitting this out of the shell wrapper is not ceremony: the edit has to find the
`pre-commit:` section, find its `commands:` map, match that map's indentation, and
replace an existing managed block without disturbing anything around it. That is
text surgery on someone else's config file, and doing it in awk is how you corrupt
a repo you do not own.

Stdlib only — this runs against arbitrary workspaces, which may have no venv.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Optional, Tuple

BEGIN_MARKER = "# >>> loregarden organization guardrails (managed) >>>"
END_MARKER = "# <<< loregarden organization guardrails (managed) <<<"

#: Command names the managed block writes. Namespaced deliberately: blobert
#: already has a `py-organization` of its own, and a second entry under the same
#: key in the same map is a duplicate YAML key — the parser either errors or
#: silently keeps one, quietly disabling the workspace's existing gate. The
#: prefix also makes provenance obvious in lefthook's output.
MANAGED_COMMAND_NAMES = ("loregarden-py-organization", "loregarden-ts-organization")

#: `**/*.py` matches nested files only — lefthook skipped a root-level `foo.py`
#: outright, reporting "no files for inspection", which reads exactly like a pass.
#: The alternation covers both depths. Verified against lefthook v2.1.10.
PY_GLOB = "{*.py,**/*.py}"
TS_GLOB = "{*.ts,*.tsx,**/*.ts,**/*.tsx}"


def render_block(loregarden_root: Path, indent: str) -> List[str]:
    scripts = loregarden_root / ".lefthook" / "scripts"
    py_name, ts_name = MANAGED_COMMAND_NAMES
    body = [
        BEGIN_MARKER,
        "# Generated by loregarden's scripts/install-workspace-hooks.sh — do not edit",
        "# by hand; re-run that script to refresh. The rules live in loregarden.",
        f"{py_name}:",
        "  name: Python organization guardrails (loregarden)",
        "  priority: 1",
        f'  glob: "{PY_GLOB}"',
        f"  run: python3 {scripts / 'py_organization_check.py'} {{staged_files}}",
        f"{ts_name}:",
        "  name: TypeScript organization guardrails (loregarden)",
        "  priority: 1",
        f'  glob: "{TS_GLOB}"',
        f"  run: node {scripts / 'ts_organization_check.cjs'} {{staged_files}}",
        END_MARKER,
    ]
    return [f"{indent}{line}" if line.strip() else line for line in body]


def colliding_commands(lines: List[str]) -> List[str]:
    """Managed names already defined outside the managed block.

    Namespacing makes this near-impossible, but writing a duplicate key into
    someone else's config is bad enough to be worth refusing rather than
    discovering later as a gate that stopped running.
    """
    defined = {
        line.strip().rstrip(":")
        for line in lines
        if line.strip().endswith(":") and not line.strip().startswith("#")
    }
    return [name for name in MANAGED_COMMAND_NAMES if name in defined]


def find_commands_map(lines: List[str]) -> Optional[Tuple[int, str]]:
    """Return (line index after `commands:`, indent for its entries).

    The entry indent is read from the first existing entry rather than assumed,
    so this matches whatever style the target repo already uses.
    """
    try:
        start = next(i for i, line in enumerate(lines) if line.startswith("pre-commit:"))
    except StopIteration:
        return None
    commands = None
    for i in range(start + 1, len(lines)):
        line = lines[i]
        if line and not line[0].isspace():
            break  # next top-level section; pre-commit had no commands map
        if line.strip() == "commands:":
            commands = i
            break
    if commands is None:
        return None

    map_indent = len(lines[commands]) - len(lines[commands].lstrip())
    entry_indent = " " * (map_indent + 2)
    for i in range(commands + 1, len(lines)):
        line = lines[i]
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if indent <= map_indent:
            break
        entry_indent = " " * indent
        break
    return commands, entry_indent


def strip_managed_block(lines: List[str]) -> Tuple[List[str], List[str]]:
    """Split out the existing managed block, if any. Returns (rest, block)."""
    out: List[str] = []
    block: List[str] = []
    inside = False
    for line in lines:
        if line.strip() == BEGIN_MARKER:
            inside = True
            block.append(line)
            continue
        if line.strip() == END_MARKER:
            inside = False
            block.append(line)
            continue
        (block if inside else out).append(line)
    return out, block


def end_of_commands_map(lines: List[str], commands_index: int, entry_indent: str) -> int:
    """First line after the commands map ends."""
    map_indent = len(lines[commands_index]) - len(lines[commands_index].lstrip())
    end = len(lines)
    for i in range(commands_index + 1, len(lines)):
        line = lines[i]
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if indent <= map_indent:
            end = i
            break
    # Do not swallow blank lines that separate sections.
    while end > commands_index + 1 and not lines[end - 1].strip():
        end -= 1
    return end


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--loregarden-root", required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    config = Path(args.config)
    original = config.read_text(encoding="utf-8").splitlines()
    rest, existing = strip_managed_block(original)

    located = find_commands_map(rest)
    if located is None:
        print(f"skip: {config} has no pre-commit commands map", file=sys.stderr)
        return 1
    collisions = colliding_commands(rest)
    if collisions:
        print(
            f"skip: {config.parent} already defines {', '.join(collisions)} outside the "
            "managed block; rename or remove it first rather than have two entries "
            "under one key",
            file=sys.stderr,
        )
        return 1

    commands_index, entry_indent = located
    block = render_block(Path(args.loregarden_root), entry_indent)

    if existing == block:
        print(f"ok: {config.parent} already current")
        return 0
    if args.check:
        state = "outdated" if existing else "missing"
        print(f"{state}: {config.parent} managed block")
        return 1

    insert = end_of_commands_map(rest, commands_index, entry_indent)
    updated = [*rest[:insert], *block, *rest[insert:]]
    config.write_text("\n".join(updated) + "\n", encoding="utf-8")
    print(f"{'refreshed' if existing else 'installed'}: {config.parent}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
