"""Publishing a Studio workflow must round-trip every stage field.

`publish_workflow` builds the template's stage dict field by field, so a field
`WorkflowStageDef` carries and the publish payload omits is dropped the first
time anyone publishes — silently, and only visible later as a gate that stopped
firing. `terminal` and `skip_when` were lost that way once; `required_evidence`
was next in line, and it is what makes the implement and verify stages of the
live loregarden template prove their work.
"""

import json

from loregarden.core.workflow_loader import get_template_stages
from loregarden.models.domain import (
    StudioWorkflowCreate,
    StudioWorkflowStage,
    WorkflowStageDef,
    WorkflowTemplate,
)
from loregarden.services.studio_service import StudioService
from sqlmodel import Session, select

# Every field StudioWorkflowStage carries beyond the identity ones, set to a
# value distinguishable from its default.
RICH_STAGE = {
    "stage_type": "agent",
    "agent_id": "planner",
    "optional": True,
    "gate_required": True,
    "skip_when": "has_description",
    "model": "claude-opus-5",
    "required_evidence": ["real_surface"],
    "checklist": ["Run the thing"],
    "stage_brief": "Do the part the reviewer cannot do for you.",
}


#: Fields that may legitimately exist on one stage model and not the other.
#: Empty on purpose — a name here is a decision someone made, not a default.
DELIBERATE_DIVERGENCE: frozenset[str] = frozenset()

#: Set by the fixture itself, so the generator must not also supply them.
_IDENTITY_FIELDS = frozenset({"key", "name", "order", "terminal"})


def _distinctive_value(name: str, info) -> object | None:
    """A value for this field that differs from its default.

    Returns None for anything this cannot synthesise, so a new field of an
    unhandled type is skipped rather than failing the suite for the wrong
    reason — the parity test above is what catches the field's arrival.
    """
    annotation = info.annotation
    if annotation is bool:
        return True
    if annotation is int:
        return 7
    if annotation is str:
        # Two fields are validated against real rows on publish, so a
        # synthesised value would fail for a reason unrelated to round-tripping.
        real = {"stage_type": "agent", "agent_id": "planner", "skill_name": "plan"}
        return real.get(name, f"{name}-value")
    if annotation == list[str]:
        return [f"{name}-entry"]
    return None


def _publish(session: Session, slug: str) -> list:
    svc = StudioService(session)
    svc.create_workflow(
        StudioWorkflowCreate(
            slug=slug,
            name="Round Trip",
            stages=[
                StudioWorkflowStage(key="work", name="Work", order=1, **RICH_STAGE),
                StudioWorkflowStage(key="done", name="Done", order=2, terminal=True),
            ],
        )
    )
    svc.publish_workflow(slug)
    template = session.exec(
        select(WorkflowTemplate).where(WorkflowTemplate.slug == f"studio-{slug}")
    ).one()
    return get_template_stages(template)


def test_the_two_stage_models_have_the_same_fields(db_session: Session):
    """AC2. `WorkflowStageDef` is what runs; `StudioWorkflowStage` is what the
    editor holds. They agree today and nothing keeps them agreeing: they are
    independent SQLModel subclasses with no shared base, so mypy cannot see the
    relationship and the publish path used to bridge them by hand.
    """
    studio = set(StudioWorkflowStage.model_fields)
    published = set(WorkflowStageDef.model_fields)

    assert studio - DELIBERATE_DIVERGENCE == published - DELIBERATE_DIVERGENCE, (
        "the Studio and published stage models have drifted; add the field to "
        "both, or name it in DELIBERATE_DIVERGENCE with a reason"
    )


def test_every_field_survives_a_publish(db_session: Session):
    """AC3 and AC6. Generated by walking the model, so a field added to both
    models and forgotten in the publish path fails here.

    The hardcoded dict this replaces could not do that: it only ever asserted
    the fields somebody remembered to list in it, which is the same failure the
    publish path had.
    """
    stage_fields = {
        name: value
        for name, value in (
            (name, _distinctive_value(name, info))
            for name, info in StudioWorkflowStage.model_fields.items()
        )
        if value is not None and name not in _IDENTITY_FIELDS
    }
    svc = StudioService(db_session)
    svc.create_workflow(
        StudioWorkflowCreate(
            slug="generated",
            name="Generated",
            stages=[
                StudioWorkflowStage(key="work", name="Work", order=1, **stage_fields),
                StudioWorkflowStage(key="done", name="Done", order=2, terminal=True),
            ],
        )
    )
    svc.publish_workflow("generated")
    template = db_session.exec(
        select(WorkflowTemplate).where(WorkflowTemplate.slug == "studio-generated")
    ).one()
    work = next(stage for stage in get_template_stages(template) if stage.key == "work")

    for name, expected in stage_fields.items():
        assert getattr(work, name) == expected, f"publish dropped or altered {name!r}"


def test_publish_round_trips_every_stage_field(db_session: Session):
    stages = {stage.key: stage for stage in _publish(db_session, "round-trip")}
    work = stages["work"]

    for field, expected in RICH_STAGE.items():
        assert getattr(work, field) == expected, f"publish dropped {field}"
    assert stages["done"].terminal is True


def test_published_json_carries_the_evidence_requirement(db_session: Session):
    """The field that matters most in practice, asserted on the stored JSON.

    `get_template_stages` fills defaults, so a stage that lost its evidence
    requirement still parses — it just parses as an empty list. Read the row.
    """
    _publish(db_session, "round-trip-json")
    template = db_session.exec(
        select(WorkflowTemplate).where(WorkflowTemplate.slug == "studio-round-trip-json")
    ).one()
    raw = {item["key"]: item for item in json.loads(template.stages_json)}

    assert raw["work"]["required_evidence"] == ["real_surface"]
    assert raw["work"]["stage_brief"] == RICH_STAGE["stage_brief"]
    assert raw["work"]["checklist"] == ["Run the thing"]
